#pragma once

#include <Eigen/Dense>

// This file has been generated by generate6LinkModelSymengine.py.
// Edit at your own risk.

enum RobotType
{
	UR3e,
	UR5e
};


class URRobot
{
public:
	URRobot();
	URRobot(RobotType type);
	~URRobot();
	int N;
	Eigen::Matrix<double, 6, 1> gravity (Eigen::Matrix<double, 6, 1> & q);

	Eigen::Matrix<double, 6, 6> jacobian (Eigen::Matrix<double, 6, 1> & q);

	Eigen::Matrix<double, 6, 6> jacobianDot (Eigen::Matrix<double, 6, 1> & q, Eigen::Matrix<double, 6, 1> & dq);

	Eigen::Matrix<double, 6, 6> inertia (Eigen::Matrix<double, 6, 1> & q);

	Eigen::Matrix<double, 6, 6> coriolis (Eigen::Matrix<double, 6, 1> & q, Eigen::Matrix<double, 6, 1> & dq);

private: 

	double a2_;
	double a3_;
	double d1_;
	double d4_;
	double d5_;
	double d6_;
	double m_[6];
	double com_[6][3];
	double link_inertia_[6][3][3];
	double g[3];
};
